version: 2
sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have on row per product_id found in each orders_id
        columns:
          - name: date_date
            description: date of purchase
          - name: orders_id
            description: Order Identification
          - name: product_id
            description: Product Identification
          - name: revenue
            description: amount of revenue
          - name: quantity
            description: amount of product ordered        
      - name: product 
        identifier: raw_gz_product
        description: products sold by Greenweez
        columns:
          - name: products_id
            description: Products Identification
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: how much is the product  
      - name: ship
        identifier: raw_gz_ship
        description: Orders shipped by Greenweez
        columns:
          - name: orders_id
            description: Order Identification
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: money customer has to pay for shipment
          - name: logcost
            description: cost for logistics
          - name: ship_cost
            description: cost for shipment
      - name: adwords
        identifier: raw_gz_adwords  
        description: how did the adwords campaigns perform
        tests:
          - unique:
              column_name: "(campaign_key || '-' || date_date)"
        columns:
          - name: date_date
            description: date the ad run
          - name:  paid_source
            description: where the ad run
          - name: campaign_key
            description: Identifier for the campaign
          - name: campaign_name
            description: name of the campaign
          - name: ads_cost
            description: money spent on the ads
          - name: impression
            description: number of views
          - name: click
            description: number of clicks          
      - name: bing
        identifier: raw_gz_bing
        description: how did the bing campaigns perform
        tests:
          - unique:
              column_name: "(campaign_key || '-' || date_date)"
        columns:
          - name: date_date
            description: date the ad run
          - name:  paid_source
            description: where the ad run
          - name: campaign_key
            description: Identifier for the campaign
          - name: campaign_name
            description: name of the campaign
          - name: ads_cost
            description: money spent on the ads
          - name: impression
            description: number of views
          - name: click
            description: number of clicks
      - name: criteo
        identifier: raw_gz_criteo
        description: how did the criteo campaigns
        tests:
          - unique:
              column_name: "(campaign_key || '-' || date_date)" 
        columns:
          - name: date_date
            description: date the ad run
          - name:  paid_source
            description: where the ad run
          - name: campaign_key
            description: Identifier for the campaign
          - name: campaign_name
            description: name of the campaign
          - name: ads_cost
            description: money spent on the ads
          - name: impression
            description: number of views
          - name: click
            description: number of clicks
      - name: facebook
        identifier: raw_gz_facebook
        description: how did the facebook campaigns perform
        tests:
          - unique:
              column_name: "(campaign_key || '-' || date_date)"
        columns:
          - name: date_date
            description: date the ad run
          - name:  paid_source
            description: where the ad run
          - name: campaign_key
            description: Identifier for the campaign
          - name: campaign_name
            description: name of the campaign
          - name: ads_cost
            description: money spent on the ads
          - name: impression
            description: number of views
          - name: click
            description: number of clicks

          